# ==============================================================================
# read_manifest.R
# Description: Reads the global manifest.json generated by the pipeline.
# ==============================================================================

read_manifest <- function(result_dir) {
  manifest_path <- file.path(result_dir, "manifest.json")
  if (!file.exists(manifest_path)) {
    stop("manifest.json not found in: ", result_dir)
  }
  jsonlite::read_json(manifest_path, simplifyVector = TRUE)
}
