# ==============================================================================
# read_summary.R
# Description: Reads per-step summary.json files generated by the pipeline.
# ==============================================================================

read_step_summary <- function(result_dir, step_summary_path) {
  path <- file.path(result_dir, step_summary_path)
  if (!file.exists(path)) return(NULL)
  jsonlite::read_json(path, simplifyVector = TRUE)
}

find_step <- function(manifest, step_name) {
  steps <- manifest$steps
  if (is.null(steps) || length(steps) == 0) return(NULL)

  if (is.data.frame(steps)) {
    step <- steps[steps$step == step_name, , drop = FALSE]
    if (nrow(step) == 0) return(NULL)
    return(step[1, , drop = FALSE])
  }

  matches <- Filter(function(x) !is.null(x$step) && identical(x$step, step_name), steps)
  if (length(matches) == 0) return(NULL)
  as.data.frame(matches[[1]], stringsAsFactors = FALSE)
}

read_summary_for_step <- function(result_dir, manifest, step_name) {
  step <- find_step(manifest, step_name)
  if (is.null(step)) return(NULL)
  read_step_summary(result_dir, step$summary[1])
}

is_step_success <- function(manifest, step_name) {
  step <- find_step(manifest, step_name)
  if (is.null(step)) return(FALSE)
  tolower(step$status[1]) == "success"
}
