# ==============================================================================
# read_summary.R
# Description: Reads per-step summary.json files generated by the pipeline.
# ==============================================================================

read_step_summary <- function(result_dir, step_summary_path) {
  path <- file.path(result_dir, step_summary_path)
  if (!file.exists(path)) return(NULL)
  jsonlite::read_json(path, simplifyVector = TRUE)
}

find_step <- function(manifest, step_name) {
  step <- manifest$steps[manifest$steps$step == step_name, , drop = FALSE]
  if (nrow(step) == 0) return(NULL)
  step
}

is_step_success <- function(manifest, step_name) {
  step <- find_step(manifest, step_name)
  if (is.null(step)) return(FALSE)
  tolower(step$status[1]) == "success"
}
